#### Web Scraping

In [46]:
import requests
from bs4 import BeautifulSoup
import IPython.display
import lxml
import pandas as pd

header = {"User-Agent": "Chrome/127.0.0.1"}
url = "https://en.wikipedia.org/wiki/World_population"
response = requests.get(url=url, headers=header)
response.raise_for_status
soup = BeautifulSoup(response.content)

In [2]:
url = "https://en.wikipedia.org/wiki/World_population"

Step - 1: Get HTML content from web page

In [35]:
headers = {"User-Agent": "Chrome/127.0.0.1"}
response = requests.get(url, headers=headers)
response.status_code

200

In [6]:
print(response.content[0:1000])

b'<!DOCTYPE html>\n<html class="client-nojs vector-feature-language-in-header-enabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 vector-feature-night-mode-enabled skin-theme-clientpref-day vector-sticky-header-enabled vector-toc-available" lang="en" dir="ltr">\n<head>\n<meta charset="UTF-8">\n<title>World population - Wikipedia</title>\n<script>(function(){var className="client-js vector-feature-language-in-header-enabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-fe'

#### Get Beautiful Soup

In [37]:
from bs4 import BeautifulSoup

soup = BeautifulSoup(response.content)

#### Show title of web page

In [47]:
title_tag = soup.find(name="title")
title_tag.text

'World population - Wikipedia'

#### How to inspect the contnet of HTML
    Right click on URL content and select Inspect menu item

In [48]:
# Headings
heading = soup.find(name="h1", class_="firstHeading")
heading.text

'World population'

In [49]:
# Sub Headings
subheadings = soup.find_all(name="div", class_="mw-heading")
subheadings_list = [tag.text for tag in subheadings]
subheadings_list.__len__()

27

In [50]:
# Paragraphs
paragraphs = soup.find_all(name="p")
paragraphs_list = [tag.text for tag in paragraphs]
paragraphs_list[0]

'\n'

In [51]:
with open("paragraphs.txt", "w", encoding="utf-8") as f:
    f.writelines(paragraphs_list)

In [59]:
# Images
images = soup.find_all(name="a", class_="mw-file-description")
print(images[0])
home_page = "https://en.wikipedia.org"
image_urls = [home_page + tag.get("href") for tag in images]
image_urls

<a class="mw-file-description" href="/wiki/File:World_Population_Prospects.svg"><img class="mw-file-element" data-file-height="676" data-file-width="900" decoding="async" height="263" src="//upload.wikimedia.org/wikipedia/commons/thumb/0/0e/World_Population_Prospects.svg/500px-World_Population_Prospects.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/0/0e/World_Population_Prospects.svg/525px-World_Population_Prospects.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/0/0e/World_Population_Prospects.svg/700px-World_Population_Prospects.svg.png 2x" width="350"/></a>

['https://en.wikipedia.org/wiki/File:World_Population_Prospects.svg',
 'https://en.wikipedia.org/wiki/File:Illustration_of_contemporary_and_past_human_populations_Our_World_in_Data.png',
 'https://en.wikipedia.org/wiki/File:2020_1million_cities.jpg',
 'https://en.wikipedia.org/wiki/File:Expectancy_of_life.svg',
 'https://en.wikipedia.org/wiki/File:Population_pyramid_of_the_world_in_continental_groupings_2023.svg',
 'https://en.wikipedia.org/wiki/File:Global_population_cartogram.png',
 'https://en.wikipedia.org/wiki/File:People%27s_-Km%C2%B2_for_all_countries_(and_us_states,_uk_kingdoms).png',
 'https://en.wikipedia.org/wiki/File:Top_5_Country_Population_Graph_1901_to_2021.svg',
 'https://en.wikipedia.org/wiki/File:Population_Density,_v4.11,_2020_(48009093621).jpg',
 'https://en.wikipedia.org/wiki/File:World_population_(UN).svg',
 'https://en.wikipedia.org/wiki/File:Total_Fertility_Rate_Map_by_Country.svg',
 'https://en.wikipedia.org/wiki/File:World_population_counter,_Eureka,_Halifax,_West_Yorkshire_(27th_August_2022)_001.jpg',
 'https://en.wikipedia.org/wiki/File:Population_curve.svg',
 'https://en.wikipedia.org/wiki/File:World_population_growth_(lin-log_scale).png',
 'https://en.wikipedia.org/wiki/File:World_population_history.svg',
 'https://en.wikipedia.org/wiki/File:Question_book-new.svg',
 'https://en.wikipedia.org/wiki/File:Population_by_broad_age_group_projected_to_2100,_OWID.svg',
 'https://en.wikipedia.org/wiki/File:Population-doubling.svg',
 'https://en.wikipedia.org/wiki/File:The_Blue_Marble,_AS17-148-22727.jpg',
 'https://en.wikipedia.org/wiki/File:Commons-logo.svg',
 'https://en.wikipedia.org/wiki/File:Emblem-money.svg']

### Get Table

In [66]:
from io import StringIO

table_tags = soup.find_all(name="table", class_="wikitable")
dfs = []
for table in table_tags:
    t = StringIO(str(table))
    df = pd.read_html(t)[0]
    dfs.append(df)
dfs[0].to_csv("table.csv", index=False)
for i in range(3):
    display(dfs[i])

      Population     1     2     3     4     5     6     7     8     9    10
0           Year  1804  1927  1960  1974  1987  1999  2011  2022  2037  2057
1  Years elapsed     –   123    33    14    13    12    12    11    15    20

,Region,2022 (percent),2030 (percent),2050 (percent)
0,Sub-Saharan Africa,"1,152 (14.51%)","1,401 (16.46%)","2,094 (21.62%)"
1,Northern Africa and Western Asia,549 (6.91%),617 (7.25%),771 (7.96%)
2,Central Asia and Southern Asia,"2,075 (26.13%)","2,248 (26.41%)","2,575 (26.58%)"
3,Eastern Asia and Southeastern Asia,"2,342 (29.49%)","2,372 (27.87%)","2,317 (23.92%)"
4,Europe and Northern America,"1,120 (14.10%)","1,129 (13.26%)","1,125 (11.61%)"
5,Latin America and the Caribbean,658 (8.29%),695 (8.17%),749 (7.73%)
6,Australia and New Zealand,31 (0.39%),34 (0.40%),38 (0.39%)
7,Oceania,14 (0.18%),15 (0.18%),20 (0.21%)
8,World,7942,8512,9687

,Region,Density (inhabitants/km2),Population (millions),Most populous country,Most populous city (metropolitan area)
0,Asia,104.1,4641,"1,439,090,595 – India","13,515,000 – Tokyo Metropolis (37,400,000 – Gr..."
1,Africa,44.4,1340,"0,211,401,000 – Nigeria","09,500,000 – Cairo (20,076,000 – Greater Cairo)"
2,Europe,73.4,747,"0,146,171,000 – Russia, approx. 110 million in...","13,200,000 – Moscow (20,004,000 – Moscow metro..."
3,Latin America,24.1,653,"0,214,103,000 – Brazil","12,252,000 – São Paulo City (21,650,000 – São ..."
4,Northern America[note 1],14.9,368,"0,332,909,000 – United States","08,804,000 – New York City (23,582,649 – New Y..."
5,Oceania,5,42,"0,025,917,000 – Australia","05,367,000 – Sydney"
6,Antarctica,~0,0.004[89],N/A[note 2],"00,001,258 – McMurdo Station"

#### Creating a class for wikpedia scrapper

In [30]:
import requests
from bs4 import BeautifulSoup
import IPython.display
from io import StringIO
import pandas as pd
import lxml


class WikiScraper:

    def __init__(self, url: str):
        self.url = url
        header = {"User-Agent": "Chrome/127.0.0.1"}
        response = requests.get(self.url, headers=header)
        response.raise_for_status()
        self.soup = BeautifulSoup(response.content)

    def get_title(self):
        title_tag = self.soup.find(name="title")
        return title_tag.text

    def get_heading(self):
        heading_tag = self.soup.find(name="h1", class_="firstHeading")
        return heading_tag.text

    def get_subheading(self):
        sub_tags = self.soup.find_all("div", class_="mw-heading")
        sub_text = [tag.text for tag in sub_tags]
        return sub_text

    def get_paras(self):
        p_tags = self.soup.find_all(name="p")
        p_text = [tag.text for tag in p_tags]
        return p_text

    def save_text(self, text: list[str], filename: str):
        with open(filename, "w", encoding="utf-8") as f:
            f.writelines(text)

    def get_image_links(self):
        a_tags = self.soup.find_all(name="a", class_="mw-file-description")
        home_page = "https://en.wikpedia.org"
        img_urls = [home_page + tag.get("href") for tag in a_tags]
        return img_urls

    def get_tables(self):
        table_tags = self.soup.find_all(name="table", class_="wikitable")
        dfs = []
        for table in table_tags:
            t = StringIO(str(table))
            df = pd.read_html(t)[0]
            dfs.append(df)
        return dfs

In [9]:
data_analysis_scraper = WikiScraper(url="https://en.wikipedia.org/wiki/Data_analysis")
data_analysis_scraper.url

'https://en.wikipedia.org/wiki/Data_analysis'

In [10]:
data_analysis_scraper.get_title()

'Data analysis - Wikipedia'

In [12]:
data_analysis_scraper.get_title()

'Data analysis - Wikipedia'

In [31]:
data_analysis_scraper.get_heading()

'Data analysis'

In [16]:
data_analysis_scraper.get_subheading()

['Data analysis process', '[edit]']

In [ ]:
data_analysis_scraper.get_paras()

'\n'

In [19]:
data_analysis_scraper.get_image_links()

['https://en.wikpedia.org/wiki/File:Rayleigh-Taylor_instability.jpg',
 'https://en.wikpedia.org/wiki/File:Data_visualization_process_v1.png',
 'https://en.wikpedia.org/wiki/File:Relationship_of_data,_information_and_intelligence.png',
 'https://en.wikpedia.org/wiki/File:Social_Network_Analysis_Visualization.png',
 'https://en.wikpedia.org/wiki/File:Total_Revenues_and_Outlays_as_Percent_GDP_2013.png',
 'https://en.wikpedia.org/wiki/File:U.S._Phillips_Curve_2000_to_2013.png',
 'https://en.wikpedia.org/wiki/File:US_Employment_Statistics_-_March_2015.png',
 'https://en.wikpedia.org/wiki/File:User-activities.png',
 'https://en.wikpedia.org/wiki/File:Wikiversity_logo_2017.svg']

In [20]:
data_analysis_scraper.save_text(
    data_analysis_scraper.get_paras(), data_analysis_scraper.get_title()
)

In [33]:
dfs = data_analysis_scraper.get_tables()
dfs.__len__()

1

In [22]:
!uv add lxml

Resolved 138 packages in 28.59s
Downloading lxml (3.8MiB)
 Downloading lxml
Prepared 1 package in 9.13s
warning: Failed to hardlink files; falling back to full copy. This may lead to degraded performance.
         If the cache and target directories are on different filesystems, hardlinking may not be supported.
         If this is intentional, set `export UV_LINK_MODE=copy` or use `--link-mode=copy` to suppress this warning.
Installed 1 package in 105ms
 + lxml==6.0.1

#### Get image links from different wikipedia urls

In [26]:
urls = [
    "https://en.wikipedia.org/wiki/Data_science",
    "https://en.wikipedia.org/wiki/Data_analysis",
    "https://en.wikipedia.org/wiki/World_population",
    "https://en.wikipedia.org/wiki/Python_(programming_language)",
]

In [28]:
img_dict = {}

for url in urls:
    print(f"Scraping : {url}")
    scraper = WikiScraper(url)
    h1_text = scraper.get_heading()
    img_links = scraper.get_image_links()
    img_dict[h1_text] = img_links

img_dict

Scraping : https://en.wikipedia.org/wiki/Data_science
Scraping : https://en.wikipedia.org/wiki/Data_analysis
Scraping : https://en.wikipedia.org/wiki/World_population
Scraping : https://en.wikipedia.org/wiki/Python_(programming_language)

{'Data science': ['https://en.wikpedia.org/wiki/File:PIA23792-1600x1200(1).jpg',
  'https://en.wikpedia.org/wiki/File:EDA_example_-_Always_plot_your_data.jpg',
  'https://en.wikpedia.org/wiki/File:Cloud_computing_in_enabling_data_science_at_scale.jpg'],
 'Data analysis': ['https://en.wikpedia.org/wiki/File:Rayleigh-Taylor_instability.jpg',
  'https://en.wikpedia.org/wiki/File:Data_visualization_process_v1.png',
  'https://en.wikpedia.org/wiki/File:Relationship_of_data,_information_and_intelligence.png',
  'https://en.wikpedia.org/wiki/File:Social_Network_Analysis_Visualization.png',
  'https://en.wikpedia.org/wiki/File:Total_Revenues_and_Outlays_as_Percent_GDP_2013.png',
  'https://en.wikpedia.org/wiki/File:U.S._Phillips_Curve_2000_to_2013.png',
  'https://en.wikpedia.org/wiki/File:US_Employment_Statistics_-_March_2015.png',
  'https://en.wikpedia.org/wiki/File:User-activities.png',
  'https://en.wikpedia.org/wiki/File:Wikiversity_logo_2017.svg'],
 'World population': ['https://en.wikpedia.org/wiki/File:World_Population_Prospects.svg',
  'https://en.wikpedia.org/wiki/File:Illustration_of_contemporary_and_past_human_populations_Our_World_in_Data.png',
  'https://en.wikpedia.org/wiki/File:2020_1million_cities.jpg',
  'https://en.wikpedia.org/wiki/File:Expectancy_of_life.svg',
  'https://en.wikpedia.org/wiki/File:Population_pyramid_of_the_world_in_continental_groupings_2023.svg',
  'https://en.wikpedia.org/wiki/File:Global_population_cartogram.png',
  'https://en.wikpedia.org/wiki/File:People%27s_-Km%C2%B2_for_all_countries_(and_us_states,_uk_kingdoms).png',
  'https://en.wikpedia.org/wiki/File:Top_5_Country_Population_Graph_1901_to_2021.svg',
  'https://en.wikpedia.org/wiki/File:Population_Density,_v4.11,_2020_(48009093621).jpg',
  'https://en.wikpedia.org/wiki/File:World_population_(UN).svg',
  'https://en.wikpedia.org/wiki/File:Total_Fertility_Rate_Map_by_Country.svg',
  'https://en.wikpedia.org/wiki/File:World_population_counter,_Eureka,_Halifax,_West_Yorkshire_(27th_August_2022)_001.jpg',
  'https://en.wikpedia.org/wiki/File:Population_curve.svg',
  'https://en.wikpedia.org/wiki/File:World_population_growth_(lin-log_scale).png',
  'https://en.wikpedia.org/wiki/File:World_population_history.svg',
  'https://en.wikpedia.org/wiki/File:Question_book-new.svg',
  'https://en.wikpedia.org/wiki/File:Population_by_broad_age_group_projected_to_2100,_OWID.svg',
  'https://en.wikpedia.org/wiki/File:Population-doubling.svg',
  'https://en.wikpedia.org/wiki/File:The_Blue_Marble,_AS17-148-22727.jpg',
  'https://en.wikpedia.org/wiki/File:Commons-logo.svg',
  'https://en.wikpedia.org/wiki/File:Emblem-money.svg'],
 'Python (programming language)': ['https://en.wikpedia.org/wiki/File:Python-logo-notext.svg',
  'https://en.wikpedia.org/wiki/File:Wikibooks-logo-en-noslogan.svg',
  'https://en.wikpedia.org/wiki/File:Guido_van_Rossum_in_PyConUS24.jpg',
  'https://en.wikpedia.org/wiki/File:Hello_World_in_Python.png',
  'https://en.wikpedia.org/wiki/File:Af-Helloworld_(C_Sharp).svg',
  'https://en.wikpedia.org/wiki/File:Python_3.13_Standrd_Type_Hierarchy-en.svg',
  'https://en.wikpedia.org/wiki/File:Tiobeindex.png',
  'https://en.wikpedia.org/wiki/File:Python_Powered.png',
  'https://en.wikpedia.org/wiki/File:Octicons-terminal.svg',
  'https://en.wikpedia.org/wiki/File:Commons-logo.svg',
  'https://en.wikpedia.org/wiki/File:Wikiquote-logo.svg',
  'https://en.wikpedia.org/wiki/File:Wikibooks-logo.svg',
  'https://en.wikpedia.org/wiki/File:Wikiversity_logo_2017.svg',
  'https://en.wikpedia.org/wiki/File:Wikidata-logo.svg',
  'https://en.wikpedia.org/wiki/File:Python-logo-notext.svg',
  'https://en.wikpedia.org/wiki/File:Symbol_portal_class.svg',
  'https://en.wikpedia.org/wiki/File:Symbol_portal_class.svg']}

In [29]:
import json

with open("images.json", "w") as f:
    content = json.dumps(img_dict, indent=4)
    f.write(content)